### ISSUE TITLE
What version is this?

### ISSUE THREAD

**Issue by DiMuRie** [TheGreyGhost/MinecraftByExample#11]
is it for forge 1.8.9???

**Comment by BlobmanThingy** [comment]
I believe this is for Forge 1.8.0
Some class files have been "extended" or "implemented" but don't exist in 1.8.8+

**Comment by TheGreyGhost** [comment]
Hi
Blobman is right, it is currently for 1.8 (i.e. 1.8.0).

I haven't tried compiling it with any higher versions yet, I'm waiting until a stable release.

Of course, if you want to try it yourself, just fork into a new 1-8-9 branch and update the build.gradle with the new information from the forge MDK's build.gradle from 1-8-9 release.  With any luck it should only be some minor changes, but no guarantees because the version updates have often been pretty painful in the past...

If you do spend the time, please send me a pull request so I can piggy-back on your work :)

Cheers
  TGG
