### ISSUE TITLE
cannot get textures to work

### ISSUE THREAD

**Issue by juliaasolinas** [TheGreyGhost/MinecraftByExample#12]
used this project and the textures don't show in mincraft

**Comment by mengy007** [comment]
Which IDE are you using? There was an issue where the resources were not being copied over to the correct place after building the project.

**Comment by juliaasolinas** [comment]
I'm using eclipse.

**Comment by TheGreyGhost** [comment]
I have had this problem on one of my installs (on a testing machine, using IDEA) and I never managed to figure out exactly what the problem was - a wrong setting somewhere I guess.  My workaround was just to copy the resource files manually, because after wasting 2 hours trying to track it down, I figured it was just easier to do the copying!

The target folder for me was
C:\Users\TGG\IdeaProjects\MinecraftByExample\build\classes\main\assets\minecraftbyexample

**Comment by lehjr** [comment]
for IDEA, add this to the end of build.gradle

```apply plugin: 'idea'
idea {
    module {
        inheritOutputDirs = true
    }
}```
