### ISSUE TITLE
Updated mappings

### ISSUE THREAD

**Issue by thommy101** [TheGreyGhost/MinecraftByExample#23]
Hi,
First off, thank you for your great examples, learned a lot of it.
A little remark on your 1.11 branch. You're explaining the use of itemStack.func_190926_b() (for example) and that it will change in the future. It already is changed. You only need to update your mappings in the build.gradle file to something more recent. In the latest mappings all itemStack changes are properly named to increase, decrease, ItemStack.EMPTY and so on.

It could save everyone some time to read, write and understand the code.

**Comment by TheGreyGhost** [comment]
Hi
thanks for the comments and the suggestion
I did think about updating the mapping, the mapping I used is the one that Forge is still using, and last time (in 1.8.9) that I tried to update to a newer version of the mapping than Forge, all hell broke loose when I tried to build it.

But I'll give it a go on a separate branch, because you're right those obfuscated names suck.

Cheers
  TGG

**Comment by TheGreyGhost** [comment]
Done.

**Comment by thommy101** [comment]
Thank you!

**Comment by TheGreyGhost** [comment]
no worries :)
