### ISSUE TITLE
1.10.2 final and 12.18.3.2185

### ISSUE THREAD

**Issue by rysson** [TheGreyGhost/MinecraftByExample#27]
Hi. First, awesome tutorial!

I use 1-10-2final branch. I see that "1.10.2-12.18.1.2011" forge is used. I see that most mods are against "12.18.3.2185". If I changed version in `build.gradle` build failed. I was trying to change mapping to "stable_29" (following by info at http://export.mcpbot.bspk.rs) but it didn't help.

I have still a lot of errors:
```
.../MinecraftByExample/build/sources/main/java/minecraftbyexample/mbe06_redstone/input/TileEntityRedstoneColouredLamp.java:48: error: cannot find symbol
      worldObj.checkLightFor(EnumSkyBlock.BLOCK, pos);
      ^
  symbol:   variable worldObj
  location: class TileEntityRedstoneColouredLamp
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
41 errors
1 warning
:compileJava FAILED
```

I'm new in modding. Do you have any idea what I screwed up? Can I use official forge for 1.10.2?

**Comment by TheGreyGhost** [comment]
Hi.  You should be able to change the forge version to 12.18.3.2185 without a problem, although I haven't tried it myself.  I would recommend you keep the mapping to the same as what Forge uses, i.e.     
mappings = "snapshot_20161111".  If you change the mapping, you will get the kind of errors that you're seeing, because objects often get renamed when the mapping is updated.

I'd suggest that you download the 1.10.2 final to a new directory, modify the build.gradle to 12.18.3.2185 and mappings = "snapshot_20161111", and then run your gradlew  setupDecompWorkspace.

Let me know if it still doesn't work and I'll try it here.  May take me a while due to other things going on at the moment.

Cheers
  TGG
