### ISSUE TITLE
Cammo block

### ISSUE THREAD

**Issue by msvdaamen** [TheGreyGhost/MinecraftByExample#42]
Is there a way that de cammo block base model also can rotated on the blockstate facing?
I have a block with the same behaviour but diffrent base model that is rotatable.

**Comment by TheGreyGhost** [comment]
Hi
Yes there is but you'll need to go a bit deeper into the model code to make it happen properly.  It's been a long time since I rummaged through the block models and rendering code, so I don't have any specific advice.  You could try asking on the Forge support forum, there are plenty of helpful folks there who know a lot more about it than I do!
http://www.minecraftforge.net/forum/forum/70-modder-support/
-TGG
