### ISSUE TITLE
1.12.2 mbe05 not working

### ISSUE THREAD

**Issue by Beethoven92** [TheGreyGhost/MinecraftByExample#58]
Example 05, the dynamic web model, seems to not work in branch 1.12.2 (and probably other earlier branches). When i place the block it just appears as the purple-black missing model block, the item in inventory is appearing normally tough (the cobweb icon). 

I checked the code multiple times, and everything seems fine, but unless i am missing something, there is no such models/block/smartblock/webmodel file in your assets folder, a path which is referenced in block_3d_web_statemapper_name.json as the model path, and is also referenced in the code of ModelLoader3DWeb class. 

So, what is this "webmodel" file supposed to contain? I even tried creating that file myself but still the problem in game persists. I am not even sure why you would have to make a reference to this smartmodel/webmodel file in the statemapper, so because of that missing file in your repository i got very confused. Maybe it got accidentally deleted? If not then i have got no clue how to solve the issue, because the code is identical to yours. Any idea how to solve that? 
Cheers

**Comment by TheGreyGhost** [comment]
Hmm that's odd.  Maybe I have stuffed it up by mistake while fixing another problem; it used to work fine in 1.12.2.
I'll have a look in the next couple of days.

**Comment by TheGreyGhost** [comment]
Howdy
I just tested it by downloading 1-12-2-final from scratch, and it seems to work fine?  I'm not sure why it's not rendering properly for you.

The "webmodel" model doesn't exist as a json, if you look in ModelLoader3DWeb::loadModel, you'll see that during loading the loadModel method checks the model name (from block_3d_web_statemapper_name.json) to see if it is "smartmodel/webmodel", and if it matches -> then it generates a custom IModel instead of trying to load a json model.

-TGG

**Comment by Beethoven92** [comment]
All right, but still a file named webmodel needs to exists, or not? And is there a way to do that without the loader checking for that path? Thank you for your time

**Comment by TheGreyGhost** [comment]
Hi
No, there is no file needed in this example. The point of this example is to show that you can use a loader to generate a dynamic model from scratch.  The name "webmodel" is just a flag that the loader can use however it wants.  Forge won't try to load a "webmodel.json" because the mbe05 loader has told Forge that it will handle the loading / model generation by itself.
Other loaders (eg wavefront object) do usually have a file yes, because they read the file to configure the model.

**Comment by Beethoven92** [comment]
Ok, this has much more sense now. Then my issue must lie somewhere in my code, i am going to investigate further on this. Thank you very much!

**Comment by TheGreyGhost** [comment]
no worries, you're welcome!
