### ISSUE TITLE
Multiple Redstone inputs from sides too

### ISSUE THREAD

**Issue by jackokring** [TheGreyGhost/MinecraftByExample#60]
I'm making something which needs 3 inputs. I'm wondering about extending Comparator.

1. Is it possible to just "tint" with colour the inbuilt one and override the output generation?
2. If I have to make a new one another way, how do I get the side input? For example, copying the Redstone meter?
3. Is there any texture resources to start making something similar to a built-in comparator?

**Comment by TheGreyGhost** [comment]
Hi
Sorry for the delayed reply
1) Yes, probably, although you should read the vanilla code for the comparator carefully because there are often "special cases" hidden within vanilla code
2) The redstone coloured lamp is probably the best example to get side inputs from different sides
3) Just use the vanilla resources I think.  I don't know of any other resources around.
Cheers
  TGG
